export {default as Header} from './Header'
export {default as NavBar} from './NavBar'
export {default as Register} from './Login/Register'
export {default as Login} from './Login/Login'
export {default as Activities} from './Create_Activities_Post'
export {default as Routines} from './Create_Routines_Post'