export {default as Header} from './Header'
export {default as NavBar} from './NavBar'
export {default as Register} from './Login/Register'
export {default as Login} from './Login/Login'
export {default as Profile} from './Profile'
export {default as Activities} from './activities'
export {default as Routines} from './routines'
export {default as MyRoutines} from './My_Routines'